import type { DifficultyProfile } from '../types/models';

export const APPROACH_THRESHOLD_TICKS = 120;
export const DEFAULT_HOLD_MS = 80;
export const DEFAULT_MIN_CONFIDENCE = 0.7;
export const TARGET_HIT_GRACE_SECONDS = 0.5;
export const DEFAULT_GATING_TIMEOUT_SECONDS = 2.5;
export const SCHEDULER_LOOKAHEAD_SECONDS = 0.15;
export const SCHEDULER_UPDATE_MS = 25;
export const PLAY_SCENE_NOTE_START_CUTOFF_SECONDS = 3;

// Increase/decrease this to tune how tall the ball jump looks on beat.
export const BALL_BOUNCE_AMPLITUDE_FACTOR = 0.8;
export const BALL_BOUNCE_AMPLITUDE_MIN_PX = 32;
export const BALL_BOUNCE_AMPLITUDE_MAX_PX = 150;

// Ghost trail tuning for the yellow ball.
export const BALL_GHOST_TRAIL_COUNT = 10;
export const BALL_GHOST_TRAIL_SAMPLE_STEP = 2;
export const BALL_GHOST_TRAIL_JUMP_INTERPOLATION_STEPS = 6;

export const SONG_SELECT_LAYOUT = {
  TITLE_MIN_PX: 34,
  TITLE_WIDTH_SCALE: 0.058,
  LABEL_MIN_PX: 14,
  LABEL_WIDTH_SCALE: 0.017,
  LOADING_LABEL_X_RATIO: 0.27,
  LOADING_LABEL_Y_RATIO: 0.24,
  LOGO_MAX_WIDTH_PX: 420,
  LOGO_WIDTH_RATIO: 0.46,
  LOGO_ASPECT_RATIO: 0.3125,
  LOGO_COMPRESS_FACTOR: 0.7,
  LOGO_MIN_TOP_PADDING_PX: 10,
  LOGO_CENTER_Y_RATIO: 0.095,
  LOGO_CENTER_Y_OFFSET_PX: 40,
  FALLBACK_TITLE_Y_SIZE_RATIO: 0.7,
  FALLBACK_TITLE_Y_RATIO: 0.09,
  FALLBACK_TITLE_Y_OFFSET_PX: 30,
  START_BUTTON_SCALE: Math.SQRT2,
  START_BUTTON_BASE_WIDTH_PX: 388,
  START_BUTTON_MAX_WIDTH_RATIO: 0.82,
  START_BUTTON_BASE_HEIGHT_PX: 62,
  START_BUTTON_HEIGHT_SCALE: 1.08,
  START_BUTTON_BOTTOM_MARGIN_PX: 16,
  SONG_GRID_BOTTOM_GAP_PX: 12,
  SIDE_LAYOUT_REF_HEIGHT_PX: 540,
  SIDE_LAYOUT_SCALE_MIN: 0.6,
  SIDE_LAYOUT_SCALE_MAX: 1,
  SIDE_BUTTON_MAX_WIDTH_PX: 300,
  SIDE_BUTTON_WIDTH_RATIO: 0.3,
  SIDE_BUTTON_CENTER_X_RATIO: 0.79,
  SIDE_BUTTONS_BOTTOM_GAP_FROM_START_PX: 14,
  DIFFICULTY_BUTTON_MAX_HEIGHT_PX: 54,
  DIFFICULTY_BUTTON_MIN_HEIGHT_PX: 42,
  DIFFICULTY_BUTTON_HEIGHT_RATIO: 0.08,
  SIDE_TOP_SAFE_INSET_MIN_PX: 20,
  SIDE_TOP_SAFE_INSET_RATIO: 0.06,
  DIFFICULTY_BUTTON_PREFERRED_Y_RATIO: 0.21,
  SIDE_MIN_INTER_BUTTON_GAP_PX: 10,
  SIDE_BUTTON_COUNT_FOR_FIT: 4,
  SIDE_BUTTON_SPAN_DIVISOR: 4.5,
  SIDE_BUTTON_PREFERRED_HEIGHT_PX: 50,
  SIDE_BUTTON_MIN_HEIGHT_PX: 30,
  SIDE_BUTTON_MAX_HEIGHT_PX: 50,
  SIDE_BUTTON_FINAL_MIN_HEIGHT_PX: 27,
  SIDE_BUTTON_FINAL_HEIGHT_TRIM_PX: 3,
  SIDE_INTER_BUTTON_GAP_PREFERRED_PX: 22,
  SIDE_INTER_BUTTON_GAP_MIN_PX: 12,
  SIDE_INTER_BUTTON_GAP_MAX_PX: 22,
  SIDE_ICON_MIN_SIZE_PX: 16,
  SIDE_ICON_MAX_SIZE_PX: 26,
  SIDE_ICON_LABEL_SIZE_RATIO: 1.5,
  SIDE_ICON_BUTTON_HEIGHT_RATIO: 0.56,
  SIDE_BUTTON_FONT_MIN_PX: 14,
  SIDE_BUTTON_FONT_BASE_MIN_PX: 17,
  SIDE_BUTTON_FONT_LABEL_PLUS_PX: 2,
  SIDE_BUTTON_FONT_HEIGHT_RATIO: 0.48,
  SIDE_ICON_X_OFFSET_RATIO: 0.33,
  SIDE_LABEL_X_OFFSET_RATIO: 0.04,
  SIDE_SUMMARY_OFFSET_MIN_PX: 16,
  SIDE_SUMMARY_BUTTON_HALF_PLUS_PX: 10,
  SIDE_SUMMARY_STEP_MINUS_PX: 6,
  SIDE_SUMMARY_FINAL_MIN_PX: 14,
  SIDE_SUMMARY_FINAL_TRIM_PX: 2,
  SIDE_SUMMARY_FONT_MIN_PX: 12,
  SIDE_SUMMARY_FONT_LABEL_MINUS_PX: 3,
  IMPORT_LABEL_FONT_MIN_PX: 13,
  IMPORT_LABEL_FONT_MINUS_PX: 1,
  IMPORT_LOG_SHARE_X_OFFSET_RATIO: 0.295,
  IMPORT_LOG_SHARE_Y_OFFSET_RATIO: 0.28,
  IMPORT_LOG_SHARE_MAX_WIDTH_PX: 102,
  IMPORT_LOG_SHARE_WIDTH_RATIO: 0.34,
  IMPORT_LOG_SHARE_HEIGHT_PX: 22,
  IMPORT_LOG_SHARE_FONT_MIN_PX: 10,
  IMPORT_LOG_SHARE_FONT_LABEL_MINUS_PX: 5,
  IMPORT_SOURCE_DEBUG_SCALE: 0.7,
  IMPORT_SOURCE_DEBUG_MAX_WIDTH_PX: 300,
  IMPORT_SOURCE_DEBUG_WIDTH_RATIO: 0.38,
  IMPORT_SOURCE_DEBUG_LEFT_MARGIN_PX: 14,
  IMPORT_SOURCE_DEBUG_BUTTON_BASE_HEIGHT_PX: 30,
  IMPORT_SOURCE_GAP_FROM_SONGS_PX: 14,
  IMPORT_SOURCE_DEBUG_MIN_CENTER_Y_OFFSET_PX: 26,
  IMPORT_SOURCE_DEBUG_TITLE_Y_OFFSET_PX: 24,
  IMPORT_SOURCE_DEBUG_TITLE_FONT_MIN_PX: 11,
  IMPORT_SOURCE_DEBUG_TITLE_FONT_LABEL_MINUS_PX: 4,
  IMPORT_SUMMARY_TRUNCATE_MIN_CHARS: 28,
  IMPORT_SUMMARY_TRUNCATE_WIDTH_SCALE: 0.036,
  HINT_Y_RATIO: 0.84,
  HINT_FONT_MIN_PX: 13,
  HINT_FONT_WIDTH_RATIO: 0.015,
  PLAY_ICON_MAX_SIZE_PX: 60,
  PLAY_ICON_LABEL_PLUS_PX: 24,
  PLAY_ICON_X_OFFSET_RATIO: 0.3,
  START_LABEL_X_OFFSET_RATIO: 0.06,
  START_LABEL_FONT_MIN_PX: 28,
  START_LABEL_FONT_LABEL_PLUS_PX: 10,
  BACKDROP_RING_X_RATIO: 0.47,
  BACKDROP_RING_Y_RATIO: 0.56,
  BACKDROP_RING_RADIUS_PRIMARY_RATIO: 0.2,
  BACKDROP_RING_RADIUS_SECONDARY_RATIO: 0.235,
  BACKDROP_RING_RADIUS_TERTIARY_RATIO: 0.17,
  BACKDROP_LINE_BASE_Y_RATIO: 0.365,
  BACKDROP_LINE_SPACING_RATIO: 0.083,
  BACKDROP_LINE_COUNT: 6,
  BACKDROP_VIGNETTE_PRIMARY_Y_RATIO: 0.84,
  BACKDROP_VIGNETTE_PRIMARY_HEIGHT_RATIO: 0.2,
  BACKDROP_VIGNETTE_SECONDARY_Y_RATIO: 0.76,
  BACKDROP_VIGNETTE_SECONDARY_HEIGHT_RATIO: 0.08,
  DIFFICULTY_DROPDOWN_FONT_MIN_PX: 15,
  DIFFICULTY_DROPDOWN_FONT_LABEL_PLUS_PX: 1,
  DIFFICULTY_DROPDOWN_PADDING_MIN_PX: 34,
  DIFFICULTY_DROPDOWN_PADDING_LABEL_RATIO: 1.8,
  DIFFICULTY_DROPDOWN_HEIGHT_MAX_PX: 54,
  DIFFICULTY_DROPDOWN_HEIGHT_MIN_PX: 42,
  DIFFICULTY_DROPDOWN_HEIGHT_RATIO: 0.08,
  IMPORT_SOURCE_TOGGLE_GAP_PX: 8,
  IMPORT_SOURCE_TOGGLE_GAP_COUNT: 2,
  IMPORT_SOURCE_TOGGLE_OPTION_COUNT: 3,
  IMPORT_SOURCE_TOGGLE_CENTER_OFFSET_RATIO: 0.5,
  IMPORT_SOURCE_TOGGLE_LABEL_FONT_MIN_PX: 11,
  IMPORT_SOURCE_TOGGLE_LABEL_FONT_LABEL_MINUS_PX: 5
} as const;

export const DIFFICULTY_PRESETS: Record<'Easy' | 'Medium' | 'Hard', DifficultyProfile> = {
  Easy: {
    allowed_strings: [6, 5, 4],
    allowed_frets: { min: 0, max: 3 },
    allowed_fingers: [1],
    avg_seconds_per_note: 2.0,
    pitch_tolerance_semitones: 3,
    max_simultaneous_notes: 1,
    gating_timeout_seconds: null
  },
  Medium: {
    allowed_strings: [6, 5, 4, 3],
    allowed_frets: { min: 0, max: 5 },
    allowed_fingers: [1, 2, 3],
    avg_seconds_per_note: 0.5,
    pitch_tolerance_semitones: 1,
    max_simultaneous_notes: 1
  },
  Hard: {
    allowed_strings: [1, 2, 3, 4, 5, 6],
    allowed_frets: { min: 0, max: 12 },
    allowed_fingers: [1, 2, 3, 4],
    avg_seconds_per_note: 0.15,
    pitch_tolerance_semitones: 0.5,
    max_simultaneous_notes: 1
  }
};

export const FINGER_COLORS: Record<number, number> = {
  0: 0xd1d5db,
  1: 0xffe05c,
  2: 0xc084fc,
  3: 0x60a5fa,
  4: 0xf87171
};
