candidate_model = "candidate-model.guitar-standard.toml"

[[takes]]
id = "01_funk1_114_ab_comp"
manifest = "../../pitch-offline-bench/input/wav/01_Funk1-114-Ab_comp.jams"
wav = "../../pitch-offline-bench/input/wav/01_Funk1-114-Ab_comp_mic.wav"

[[takes]]
id = "04_jazz1_200_b_comp"
manifest = "../../pitch-offline-bench/input/wav/04_Jazz1-200-B_comp.jams"
wav = "../../pitch-offline-bench/input/wav/04_Jazz1-200-B_comp_mic.wav"

[[takes]]
id = "01_funk2_119_g_comp"
manifest = "../../pitch-offline-bench/input/wav/01_Funk2-119-G_comp.jams"
wav = "../../pitch-offline-bench/input/wav/01_Funk2-119-G_comp_mic.wav"

[[takes]]
id = "05_jazz3_150_c_comp"
manifest = "../../pitch-offline-bench/input/wav/05_Jazz3-150-C_comp.jams"
wav = "../../pitch-offline-bench/input/wav/05_Jazz3-150-C_comp_mic.wav"

[[takes]]
id = "01_funk3_98_a_comp"
manifest = "../../pitch-offline-bench/input/wav/01_Funk3-98-A_comp.jams"
wav = "../../pitch-offline-bench/input/wav/01_Funk3-98-A_comp_mic.wav"
